#
# This file contains configuration flags to customize your site
#

# Title of your site (displayed in the header)
title: "@yatabani.com"

# Short bio or description (displayed in the header)
description: Yasir O. Atabani, Cozeit, Inc.

# Author name
author: Yasir O. Atabani

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/153498?s=400&u=89107321f05605f2add3264371ffaec861f9a4e0&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
links:
  dribbble:
  email:
  facebook:
  flickr:
  github: yatabani
  instagram: yatabani
  linkedin: yatabani
  pinterest: yatabani
  rss: yes
  twitter: yatabani
  stackoverflow: users/1676446/yatabani
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: yatabani
enable_comments: True

#Theme
theme: jekyll-theme-minimal

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:  UA-67546811-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://yatabani.com"

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.0.0
paginate: 5
paginate_path: "/page/:num/"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
